### ISSUE TITLE
Publish to Docker Hub

### ISSUE THREAD

**Issue by ptpt** [valhalla/docker#3]
At https://github.com/valhalla/meili/issues/43 @chrisfosterelli suggested it would be nice to publish the docker image to Docker Hub. It's probably in the plan so I forward it to here as a reminder.

**Comment by kevinkreiser** [comment]
yep we are working on dockerizing ALL THE THINGS. I know we have docker containers already but they only expose the simple version of the routing service. We are working to rectify this and will be pushing said images to docker hub.

**Comment by heffergm** [comment]
Both the source and ppa builds are already on docker hub. However, I would stress that this is very much a work in progress. https://hub.docker.com/u/mapzen/dashboard/

**Comment by chrisfosterelli** [comment]
@heffergm Are you able to elaborate a bit on how I could use those published images? Are they a drop-in replacement for the meili docker image that has to be manually built?

**Comment by heffergm** [comment]
I'm not familiar with meili. The docker images as they currently exist in this repository simply run the valhalla routing service and serve any tile data found in /data/valhalla. 

So as per the readme, if you're just doing this locally, you can clone the repository and run:

`VALHALLA_DOCKER_DATAPATH=/some/path/to/data docker-compose -f docker-compose-{ppa|source}.yml up`.

**Comment by kevinkreiser** [comment]
@chrisfosterelli we dont yet run meili as part of these images. its really hardly any work to set it up though. currently meili's service is not run as part of the other services (skadi is also this way). both of them would either need their own images (probably what we will do) or some refactoring needs to be done in the code to make it so that there is one server to run all services (also possible but probably longer term goal)

**Comment by chrisfosterelli** [comment]
That makes sense @kevinkreiser. Should we open a new issue here to publish meili as a separate image then? I'm not super familiar with the rest of valhalla so my apologies if this is the wrong place to make that issue.

My initial issue (https://github.com/valhalla/meili/issues/43) was raised because building the meili image manually takes quite a while and requires a fair amount of RAM... it could save lots of people a bunch of time by publishing it on Docker Hub.

**Comment by kevinkreiser** [comment]
@chrisfosterelli no worries, yeah please open up an issue specific to creating an image for meili and we can take a look at making a few tweaks to the existing stuff!

**Comment by chrisfosterelli** [comment]
Sure, made https://github.com/valhalla/docker/issues/4
